AgitApiBundle_call:
    pattern:  /api/{namespace}/{class}.{method}.{_format}
    defaults: { _controller : AgitApiBundle:Api:call, _format : json }
    host: %agit.common.domain.app%
    requirements:
        path: ".*"
    methods:   [GET, POST, OPTIONS]
