services:

# registering our OWN plugins, i.e. basic endpoints, objects and formatters

    agit.api.endpoint.plugins:
        private: true
        class: ApiPluginListener
        factory_service:  agit.api.endpoint.listener.factory
        factory_method:   create
        arguments: [ common.v1, AgitApiBundle:Api:Endpoint ]
        tags: [{ name: kernel.event_listener, event: agit.api.endpoint, method: onRegistration }]

    agit.api.object.plugins:
        private: true
        class: ApiPluginListener
        factory_service:  agit.api.object.listener.factory
        factory_method:   create
        arguments: [ common.v1, AgitApiBundle:Api:Object ]
        tags: [{ name: kernel.event_listener, event: agit.api.object, method: onRegistration }]

    agit.api.formatter.plugins:
        private: true
        class: ApiPluginListener
        factory_service:  agit.api.formatter.listener.factory
        factory_method:   create
        arguments: [ common.v1, AgitApiBundle:Api:Formatter ]
        tags: [{ name: kernel.event_listener, event: agit.api.formatter, method: onRegistration }]
