services:

    agit.api.endpoint:
        class: Agit\ApiBundle\Service\EndpointService
        arguments: [ @agit.pluggable.cache.loader_factory, @service_container ]
        tags: [{ name: agit.pluggable, type: api.endpoint }]

    agit.api.object:
        class: Agit\ApiBundle\Service\ObjectService
        arguments: [ @agit.pluggable.cache.loader_factory, @service_container ]
        tags: [{ name: agit.pluggable, type: api.object }]

    agit.api.formatter:
        class: Agit\ApiBundle\Service\FormatterService
        arguments: [ @agit.pluggable.cache.loader_factory, @service_container ]
        tags: [{ name: agit.pluggable, type: api.formatter }]


    # Processor factories for pluggable API services

    agit.api.pluggable.processor_factory.endpoint:
        private: true
        class: Agit\ApiBundle\Pluggable\EndpointProcessorFactory
        arguments: [ @annotation_reader, @agit.common.cache.persistent ]
        tags: [{ name: agit.pluggable.processor_factory, type: api.endpoint }]

    agit.api.pluggable.processor_factory.object:
        private: true
        class: Agit\ApiBundle\Pluggable\ObjectProcessorFactory
        arguments: [ @annotation_reader, @agit.common.cache.persistent ]
        tags: [{ name: agit.pluggable.processor_factory, type: api.object }]

    agit.api.pluggable.processor_factory.formatter:
        private: true
        class: Agit\ApiBundle\Pluggable\FormatterProcessorFactory
        arguments: [ @annotation_reader, @agit.common.cache.persistent ]
        tags: [{ name: agit.pluggable.processor_factory, type: api.formatter }]


    # various other services

    agit.api.csrf:
        class: Agit\ApiBundle\Service\CsrfTokenService
        arguments: [@session]

    agit.api.twig:
        class: Agit\ApiBundle\Twig\ApiExtension
        arguments:  [ @agit.common.url, @agit.api.csrf ]
        tags: [{ name: twig.extension }]

    # simple form builder for API objects
    agit.api.twig.formbuilder:
        class: Agit\ApiBundle\Twig\ApiFormBuilderExtension
        arguments:  [ @?twig, @agit.api.object ]
        tags: [{ name: twig.extension }]
