services:

    agit.api.endpoint:
        class: Agit\ApiBundle\Service\EndpointService
        arguments: [ @agit.pluggable.cache.loader_factory, @service_container ]
        tags: [{ name: agit.pluggable, type: cache, tag: agit.api.endpoint, baseClass: Agit\ApiBundle\Plugin\AbstractApiEndpointPlugin }]

    agit.api.object:
        class: Agit\ApiBundle\Service\ObjectService
        arguments: [ @agit.pluggable.cache.loader_factory, @service_container ]
        tags: [{ name: agit.pluggable, type: cache, tag: agit.api.object, baseClass: Agit\ApiBundle\Plugin\AbstractApiObjectPlugin }]

    agit.api.formatter:
        class: Agit\ApiBundle\Service\FormatterService
        arguments: [ @agit.pluggable.cache.loader_factory, @service_container ]
        tags: [{ name: agit.pluggable, type: cache, tag: agit.api.formatter, baseClass: Agit\ApiBundle\Plugin\AbstractApiFormatterPlugin }]

    agit.api.csrf:
        class: Agit\ApiBundle\Service\CsrfTokenService
        arguments: [@session]

    agit.api.twig:
        class: Agit\ApiBundle\Service\TwigExtension
        arguments:  [ @agit.common.url, @agit.api.csrf ]
        tags: [{ name: twig.extension }]
